name: publish

on:
  push:
    branches:
      - release_tests
jobs:
  windows:
    runs-on: windows-2022
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: CMake Build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
          %SystemRoot%\System32\tar.exe -a -c -f out.zip build/city.exe data/*
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: out.zip
          draft: false
          prerelease: true
          generate_release_notes: true
