name: publish

on:
  push:
    branches:
      - releases
    tags:
      - v*
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2022]
        include:
          - os: ubuntu-24.04
            zip_type: linux-x64.tar.gz
            exe: city
          - os: windows-2022
            zip_type: windows-x64.zip
            exe: city.exe
    env:
      ZIP_NAME: DTCity-${{ github.ref_name }}-${{ matrix.zip_type }}
    runs-on: ${{ matrix.os}}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest
      - uses: lukka/run-vcpkg@v11 # Always specify the specific _version_ of the
      - name: Build Windows
        if: matrix.os == 'windows-2022'
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          cmake --preset=release-windows
          cmake --build build --target clang-tidy-check
          cmake --build build
          %SystemRoot%\System32\tar.exe -a -c -f ${{ env.ZIP_NAME }} data -C build ${{ matrix.exe }} -C ../docs usage-guide.pdf
      - name: Build Linux
        if: matrix.os == 'ubuntu-24.04'
        shell: bash
        run: |
          git clone https://github.com/microsoft/vcpkg.git ~/vcpkg
          cd ~/vcpkg
          ./bootstrap-vcpkg.sh
          cd $GITHUB_WORKSPACE
          VCPKG_ROOT=~/vcpkg
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev xorg-dev libwayland-dev libxkbcommon-dev wayland-protocols extra-cmake-modules
          cmake --preset=release-linux
          cmake --build build --target clang-tidy-check
          cmake --build build
          tar -czf ${{ env.ZIP_NAME }} data -C build ${{ matrix.exe }} -C ../docs usage-guide.pdf

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            ${{ env.ZIP_NAME }}
            docs/usage-guide.pdf
          draft: false
          prerelease: false
          generate_release_notes: true
