name: publish

on:
  push:
    branches:
      - release_tests
    tags:
      - "*"
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2022]
        include:
          - os: ubuntu-24.04
            zip_type: linux-x64.tar.gz
          - os: windows-2022
            zip_type: windows-x64.zip
    env:
      ZIP_NAME: DTCity-${{ github.ref_name }}-${{ matrix.zip_type }}
    runs-on: ${{ matrix.os}}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Windows
        if: matrix.os == 'windows-2022'
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
          %SystemRoot%\System32\tar.exe -a -c -f ${{ env.ZIP_NAME }} build/city.exe data/*
      - name: Build Linux
        if: matrix.os == 'ubuntu-24.04'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev xorg-dev libwayland-dev libxkbcommon-dev wayland-protocols extra-cmake-modules
          chmod +x tools/linux/glslangValidator
          cmake -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
          tar -czf ${{ env.ZIP_NAME }} build/city data/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          tag_name: ${{ github.ref_name }}
          files: ${{ env.ZIP_NAME }}
          draft: false
          prerelease: true
          generate_release_notes: true
