name: publish

on:
  push:
    branches:
      - release_tests
    tags:
      - "*"
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]
        include:
          - os: ubuntu-22.04
            zip_type: linux-x64
          - os: windows-2022
            zip_type: windows-x64
    env:
      APP_NAME: DTCity
      ZIP_NAME: ${{env.APP_NAME}}-${{ github.ref_name }}-${{ matrix.zip_type }}.zip
    runs-on: ${{ matrix.os}}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: CMake Build
        if: matrix.os == 'windows-2022'
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
          %SystemRoot%\System32\tar.exe -a -c -f ${{ env.ZIP_NAME }}.zip build/city.exe data/*
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          tag_name: ${{ github.ref_name }}
          files: ${{ env.ZIP_NAME }}
          draft: false
          prerelease: true
          generate_release_notes: true
